version: "3.7"
services:
  fastapi:
    build: ./fastapi
    volumes:
      - ./fastapi:/src
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      DB_NAME: hacku-kosen-2022-backend
      DB_ENGINE: django.db.backends.mysql
      DB_USER: fastapi
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PORT: 3306
      ENV_STATE: local
    env_file:
      - fastapi/fastapi.env
    links:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hacku-kosen-2022-backend
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

volumes:
  mysql_data:
