openapi: 3.0.3
info:
  title: YounGeek HackU Kosen 2022 - OpenAPI 3.0
  description: |-
    HackU Kosen 2022 でYounGeekが実装するAPIスキーマ
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: our HackU Kosen 2022 Repository
  url: https://github.com/youngeek-0410/hacku-kosen-2022
servers:
  - url: http://localhost:8080
paths:
  /api/projects:
    post:
      tags:
        - project
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProjectResponse'
  /api/projects/{project_id}:          
    get:
      tags:
        - project
      parameters:
        - name: project_id
          in: path
          description: ID of project to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProjectResponse'         
components:
  schemas:
    CreateProjectRequest:
      type: object
      properties:
        receiver_name:
          type: string
          description: デジタル色紙を渡す相手の名前     
    CreateProjectResponse:
      type: object
      properties:
        project_id:
          type: string
          description: 作成されたプロジェクトのID
    GetProjectResponse:
      type: object
      properties:
        project_id:
          type: string
          description: プロジェクトのID
        receiver_name:
          type: string
          description: デジタル色紙を渡す相手の名前
