name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}
  PORT: 8000

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Authenticate to GCP
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          create_credentials_file: "true"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTIFY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_MAIL_ADDRESS }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Configure Docker to use the gcloud CLI
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: IMAGE=$IMAGE docker-compose -f docker-compose.prod.yaml build

      - name: Push the docker image to Container Registry
        run: IMAGE=$IMAGE docker-compose -f docker-compose.prod.yaml push

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --port $PORT \
            --project $GCP_PROJECT_ID \
            --region $GCP_REGION \
            --platform=managed \
            --allow-unauthenticated \
            --quiet
